global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'host-metrics'
    static_configs:
      - targets: ['172.28.71.18:9100']

  - job_name: 'vm-metrics'
    static_configs:
      - targets: ['192.168.122.17:9100']
